# Generated by Django 5.2.10 on 2026-01-13 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelitemrate',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.item'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
